### ISSUE TITLE
I18n 'does not have unused keys' spec raises "[WARN] 'faq.answers' was a leaf, now has children (value <- scope conflict)"

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1176]
This happens when I run the following test: https://github.com/thewca/worldcubeassociation.org/blob/bcb1b3682f8d5f32ea588c9107c68ad4cc0aec0e/WcaOnRails/spec/i18n_spec.rb#L13

```ruby
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> bin/rspec spec/i18n_spec.rb:13
Running via Spring preloader in process 25523
Run options: include {:locations=>{"./spec/i18n_spec.rb"=>[13]}}

Randomized with seed 24574

I18n
spring app    | WcaOnRails | started 5 secs ago | test mode: [WARN] 'faq.answers' was a leaf, now has children (value <- scope conflict)
  does not have unused keys

Finished in 6.55 seconds (files took 0.09974 seconds to load)
1 example, 0 failures

Randomized with seed 24574
```

https://github.com/glebm/i18n-tasks/issues/158#issuecomment-273872322 is an example of some other people with the same issue. It sounds like the problem is that i18n-tasks sees [this line of code](https://github.com/thewca/worldcubeassociation.org/blob/bcb1b3682f8d5f32ea588c9107c68ad4cc0aec0e/WcaOnRails/app/views/static_pages/faq.html.erb#L35):

```ruby
      <% t('faq.answers', locale: :en).each do |key, faq| %>
```

and incorrectly concludes that `faq.answers` is a string. Then, when looking through our translations, it freaks out when it sees us adding children to it:

```yaml
  faq:
    title: "Frequently Asked Questions"
    contact_html: "If none of these answers helped, please %{contact_us}!"
    contact_us: "contact us"
    search_for_competition: "Search for a competition here:"
    already_logged_in: "You are already logged in with a WCA account."
    create_an_account: "You can create an account %{here}."
    claim_your_wca_id: "You can claim your WCA ID %{here}."
    create_an_account_and_claim: "Create an account %{here}. After you log in with your new account, you will be asked to claim your WCA ID."
    answers:
      '1':
        title: "How do I obtain a WCA ID and a WCA profile?"
        #context: Answer to "How do I obtain a WCA ID..."
        content:
          '1': "If you have never competed before, go to a <a href='/competitions'>competition</a>!  A WCA ID and WCA profile will be created for you when the results from your first competition are published."
```

It [sounds like](https://github.com/glebm/i18n-tasks/issues/158#issuecomment-273905065) one solution is to add `faq.answers` to our `ignore`. What do you think, @viroulep?
